### ISSUE TITLE
Version 1.1.0 is not backward compatible with 1.0.7

### ISSUE THREAD

**Issue by JDGrimes** [phpDocumentor/Reflection#96]
It updates the version of PHP-Parser dependency, and this is a breaking update—the new version of PHP-Parser uses namespaces, the old does not.

See https://github.com/WordPress/phpdoc-parser/issues/177

**Comment by jaapio** [comment]
I agree with you that we had to follow the semantic versioning here. But since this new release was a hotfix because version 2 was waiting to long and won't be compatible with version 1. I had to create some in between version. 

Logically I would have called it version 2.0.0. But since that was already reserved. I had to create a 1.1.0 release? Any suggestions how to solve this?

**Comment by jaapio** [comment]
We decided to drop our 1.1.0 release. And skip v2. The former 1.1.0 release is now named v3.

**Comment by JDGrimes** [comment]
Thanks @jaapio. Sorry for being a pain. 😈
