### ISSUE TITLE
tag a new version with latest stable dependencies ?

### ISSUE THREAD

**Issue by BenoitLeveque** [phpDocumentor/Reflection#98]
@jaapio any chance to have a new tag which use the last stable version of phpdocumentor/reflection-docblock ?

**Comment by jaapio** [comment]
I think we can't since the api of phpdocumentor/reflection-docblock was changed in version 3. Version 2.0.0-alpha2 is using this. But that doesn't have a stable api yet.  

We don't have plans to support phpdocumentor/reflection-docblock v3 in phpdocumentor/reflection v3. 

phpdocumentor/reflection v4 will support v3 but that's still under development

**Comment by BenoitLeveque** [comment]
Ok thanks for your answer.
